root: true
globals:
  notify: readonly
  DEFAULT_SETTINGS: readonly
env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 2019
plugins:
  - prettier
rules:
  prettier/prettier: error
extends:
  - eslint:recommended
  - prettier
